name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --password $SUPABASE_DB_PASSWORD --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db lint --linked

      - name: Run Supabase DB Tests
        run: |
          result=$(supabase db test --linked)
          echo "$result"
          # Verifica si el resultado contiene "Result: PASS" o "Result: NOTESTS"
          if echo "$result" | grep -q "Result: PASS"; then
            echo "Database tests passed!"
          elif echo "$result" | grep -q "Result: NOTESTS"; then
            echo "No database tests found. Skipping..."
          else
            echo "Database tests failed!"
            exit 1
          fi
