name: CI FE E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npx nuxi build

      - name: Start server
        run: npx nuxi start
        env:
          SUPABASE_URL: ${{ env.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

      - name: Check server status
        run: curl -i http://localhost:3000

      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_URL: ${{ env.CYPRESS_URL }}
          CYPRESS_SUPABASE_URL: ${{ env.SUPABASE_URL }}
          CYPRESS_SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
