name: CI FE E2E

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run E2E tests
        uses: cypress-io/github-action@v6
        env:
          SUPABASE_URL: ${{ env.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CYPRESS_URL: https://socialfilms.nuxt.dev
          CYPRESS_SUPABASE_URL: ${{ env.SUPABASE_URL }}
          CYPRESS_SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
        with:
          build: npx nuxi build
          start: npx nuxi start
          wait-on: "http://127.0.0.1:3000"
